+++
title = 'GihubでPushできない'
date = 2024-01-07T11:52:14+09:00
tags = ["bug"]
+++

GithubでPushするときに、たまに下記のエラーが出る。

`fatal: unable to access 'https://github.com/xxxxxxxxxx/xxx.git/': Could not resolve host: github.com `

その場合は`/etc/resolv.conf`を開いて`nameserver`の値を`8.8.8.8`に書き換えている。
ただ、しばらくしてから  Pushしたタイミングで上記のエラーが出るので、`resolv.conf`の値が元に戻ってることがわかる。

Network Managerが書き換えているらしいんだけど、ずっと`8.8.8.8`のままになっててほしい。

やり方はいろいろ探したら出てくるけど、めんどくさそうなので、また今度。

